/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e1e0ff",
        "on-background": "#dae2fd",
        "surface-dim": "#0b1326",
        "on-tertiary": "#502400",
        "on-secondary": "#490080",
        "secondary-fixed": "#f0dbff",
        "on-primary-fixed": "#07006c",
        "surface-variant": "#2d3449",
        "background": "#0b1326",
        "tertiary-container": "#df7412",
        "secondary": "#ddb7ff",
        "on-error": "#690005",
        "error-container": "#93000a",
        "surface-bright": "#31394d",
        "on-tertiary-container": "#461f00",
        "tertiary-fixed": "#ffdcc6",
        "surface-container-low": "#131b2e",
        "surface-tint": "#c0c1ff",
        "primary": "#c0c1ff",
        "secondary-container": "#6f00be",
        "inverse-surface": "#dae2fd",
        "secondary-fixed-dim": "#ddb7ff",
        "outline": "#8c909f",
        "on-tertiary-fixed-variant": "#723600",
        "on-error-container": "#ffdad6",
        "primary-container": "#8083ff",
        "on-secondary-container": "#d6a9ff",
        "surface": "#0b1326",
        "outline-variant": "#424754",
        "on-surface-variant": "#c2c6d6",
        "on-secondary-fixed-variant": "#6900b3",
        "surface-container-lowest": "#060e20",
        "inverse-primary": "#494bd6",
        "tertiary-fixed-dim": "#ffb786",
        "on-primary-container": "#0d0096",
        "surface-container-high": "#222a3d",
        "on-tertiary-fixed": "#311400",
        "tertiary": "#ffb786",
        "surface-container-highest": "#2d3449",
        "on-primary": "#1000a9",
        "on-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "on-primary-fixed-variant": "#2f2ebe",
        "primary-fixed-dim": "#c0c1ff",
        "error": "#ffb4ab",
        "surface-container": "#171f33",
        "on-secondary-fixed": "#2c0051"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "inter": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
